Add tests/__init__.py to fix VSCode test discovery
VSCode appears to need the tests directory to be importable to run the unit tests directly, so we need to add a (blank) `test/__init__.py` file. E.g. I was getting this error before adding the __init__.py file:

2026-07-07 12:08:19.287 [error] Unittest test discovery error for workspace:  /Users/ortk2/Dropbox/science/planetmapper
 Traceback (most recent call last):
  File "/Users/ortk2/.vscode/extensions/ms-python.python-2026.4.0-darwin-arm64/python_files/unittestadapter/discovery.py", line 80, in discover_tests
    suite = loader.discover(start_dir, pattern, top_level_dir)
  File "/Users/ortk2/miniconda3/envs/py314/lib/python3.14/unittest/loader.py", line 334, in discover
    raise ImportError('Start directory is not importable: %r' % start_dir)
ImportError: Start directory is not importable: '/Users/ortk2/Dropbox/science/planetmapper/tests'